[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  included_files = ["netlify/functions/panels/**"]
  node_bundler = "esbuild"
  external_node_modules = []

[functions."generate"]
  timeout = 26

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
